"""Stub file for custom_components/reflex_plasma_ui/plasma_ui.py"""

# ------------------- DO NOT EDIT ----------------------
# This file was generated by `reflex/utils/pyi_generator.py`!
# ------------------------------------------------------
from collections.abc import Mapping, Sequence
from typing import Any, Literal, TypeAlias

import reflex as rx
from reflex.utils.imports import ImportDict
from reflex_base.event import (
    EventType,
    PointerEventInfo,
)
from reflex_base.vars.base import Var
from reflex_components_core.core.breakpoints import Breakpoints

MoodName: TypeAlias = Literal["tidal", "aurora", "ember"]
ThemeName: TypeAlias = Literal["auto", "light", "dark"]
MaterialName: TypeAlias = Literal[
    "plasma", "crystal", "metal", "mercury", "wood", "stone", "cloud"
]
GroundName: TypeAlias = Literal["field", "clear"]

class _PlasmaBase(rx.Component):
    def add_imports(self) -> ImportDict: ...
    @classmethod
    def create(
        cls,
        *children,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> _PlasmaBase:
        """Create the component.

        Args:
            *children: The children of the component.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """

class PlasmaProvider(_PlasmaBase):
    def add_custom_code(self) -> list[str]: ...
    @classmethod
    def create(
        cls,
        *children,
        name: Var[str] | str | None = None,
        background_selector: Var[str] | str | None = None,
        mood: Literal["aurora", "ember", "tidal"]
        | Var[Literal["aurora", "ember", "tidal"] | dict[str, Any]]
        | dict[str, Any]
        | None = None,
        theme: Literal["auto", "dark", "light"]
        | Var[Literal["auto", "dark", "light"]]
        | None = None,
        background: Var[str] | str | None = None,
        radius: Var[float] | float | None = None,
        blend: Var[float] | float | None = None,
        tint: Var[str] | str | None = None,
        opacity: Var[float] | float | None = None,
        frost: Var[float] | float | None = None,
        elevation: Var[float] | float | None = None,
        smoothness: Var[float] | float | None = None,
        refraction: Var[float] | float | None = None,
        dispersion: Var[float] | float | None = None,
        rim: Var[float] | float | None = None,
        rim_color: Var[str] | str | None = None,
        rim_width: Var[float] | float | None = None,
        highlight: Var[float] | float | None = None,
        edge_line: Var[float] | float | None = None,
        shimmer: Var[float] | float | None = None,
        shimmer_speed: Var[float] | float | None = None,
        glow: Var[float] | float | None = None,
        wash: Var[float] | float | None = None,
        grain: Var[float] | float | None = None,
        background_blur: Var[float] | float | None = None,
        ground: Literal["clear", "field"]
        | Var[Literal["clear", "field"]]
        | None = None,
        preserve_drawing_buffer: Var[bool] | bool | None = None,
        material: Literal[
            "cloud", "crystal", "mercury", "metal", "plasma", "stone", "wood"
        ]
        | Var[
            Literal["cloud", "crystal", "mercury", "metal", "plasma", "stone", "wood"]
        ]
        | None = None,
        light_dir: Var[list[float]] | list[float] | None = None,
        roughness: Var[float] | float | None = None,
        anisotropy: Var[float] | float | None = None,
        edge: Var[float] | float | None = None,
        edge_scale: Var[float] | float | None = None,
        edge_sharpness: Var[float] | float | None = None,
        thickness: Var[float] | float | None = None,
        tension: Var[float] | float | None = None,
        viscosity: Var[float] | float | None = None,
        stretch: Var[float] | float | None = None,
        flow: Var[float] | float | None = None,
        form_in: Var[bool] | bool | None = None,
        form_speed: Var[float] | float | None = None,
        form_out: Var[bool] | bool | None = None,
        pointer_drop: Var[bool] | bool | None = None,
        pointer_pull: Var[bool] | bool | None = None,
        ambient_drops: Var[bool] | bool | None = None,
        grid: Var[float] | float | None = None,
        magnet: Var[float] | float | None = None,
        quality: Var[float] | float | None = None,
        freeze_on_scroll: Var[bool] | bool | None = None,
        max_surfaces: Var[int] | int | None = None,
        z_index: Var[int] | int | None = None,
        canvas: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_ready: EventType[()] | EventType[dict[str, bool]] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> PlasmaProvider:
        """Create the component.

        Args:
            *children: The children of the component.
            name: Registry name for pulse()/bump(). Default "default". Give overlay providers their own name.
            background_selector: CSS selector of an img/canvas/video element to use as the background, e.g. "canvas.ground" for a clear-ground overlay. Takes precedence over `background`.
            mood: Preset ("tidal", "aurora", "ember") or a custom mood {colors: [base, mid, accent], blend: px, spring: {stiffness, damping}}.
            theme: "auto" follows the OS and <html data-theme>. Tip: theme=rx.color_mode_cond("light", "dark").
            background: CSS color (luminance drift) or image URL / data URI (refracted, slow swirl). Omit for the mood field.
            radius: Default corner radius (px) for every surface. Default 26.
            blend: Distance (px) at which surfaces start to fuse. Default: the mood's.
            tint: Plasma tint color (hex). Default "#ffffff".
            opacity: Tint strength, 0 (clear) to 1 (solid). Default 0.
            frost: Translucency, 0 (clear) to 1 (frosted). Default 0.
            elevation: Shadow depth, 0 (flat) to 1 (floating). Default 0.35.
            smoothness: Outline smoothing strength. Default 1.
            refraction: Lens strength. Default 1.
            dispersion: Color splitting. Default 1.
            rim: Colored rim strength; 0 turns it off. Default 1.
            rim_color: "iridescent", "tint" (each surface's tint) or a hex color.
            rim_width: How far the rim reaches in from the edge. Default 1.
            highlight: Pointer-facing highlight; 0 turns it off. Default 1.
            edge_line: Thin line along the outline; 0 turns it off. Default 1.
            shimmer: Iridescent sheen drifting across each surface. Default 1.
            shimmer_speed: How fast that sheen drifts. Default 1.
            glow: Halo the plasma casts on the background. Default 1.
            wash: The material's own cast on what is seen through it. Default 1.
            grain: Film grain over the background. Default 1.
            background_blur: Blur the whole background, CSS px 0-40. Default 0.
            ground: "field" paints the background; "clear" leaves the canvas transparent (overlay providers).
            preserve_drawing_buffer: Keep frames so another provider can sample this canvas. Fixed at creation.
            material: plasma, crystal, metal, mercury, wood, stone or cloud. Default plasma.
            light_dir: [x, y, z] light direction. Default up-left, front.
            roughness: Metal finish: 0 mirror, 1 chalk. Default 0.28.
            anisotropy: Highlight stretch along the grain. Default 0.
            edge: Outline displacement from the rounded box, px. Default 0.
            edge_scale: Displacement size, cycles/px. Default 0.01.
            edge_sharpness: 0 rolls the displaced edge, 1 breaks it. Default 0.
            thickness: Panel thickness as a solid, px. Default 18.
            tension: Surface tension (bead pull, merge eagerness). Default 0.
            viscosity: 0 watery/bouncy, 1 syrup; scales drag/snap springs. Default 0.5.
            stretch: How far the plasma trails moving panels; 0 off. Default 1.
            flow: Slow ripple along the edges. Default 0.
            form_in: New surfaces grow from nothing. Default True.
            form_speed: Form in/out speed multiplier. Default 1.
            form_out: Removed surfaces shrink away. Default False.
            pointer_drop: Liquid drop following the pointer. Default True.
            pointer_pull: Surfaces swell toward a nearby pointer. Default True.
            ambient_drops: Decorative orbiting drops. Default False.
            grid: Snap grid size, px. Default 24.
            magnet: Edge latch distance, px. Default 40.
            quality: Maximum canvas pixel ratio. Default 1.25.
            freeze_on_scroll: Touch only: pin the frame during a fling. Default False.
            max_surfaces: Visible surface budget (recompiles shaders). Default 16.
            z_index: Canvas z-index. Default -1.
            canvas: False: render plasma_canvas() yourself. Default True.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_ready: Fires once the renderer exists (or WebGL2 is missing): {"supported": bool, "reduced_motion": bool}.
            **props: The props of the component.

        Returns:
            The component.
        """

class Plasma(_PlasmaBase):
    def add_custom_code(self) -> list[str]: ...
    @classmethod
    def create(
        cls,
        *children,
        as_: Var[str] | str | None = None,
        radius: Var[float] | float | None = None,
        lean: Var[bool | float] | bool | float | None = None,
        tint: Var[str] | str | None = None,
        opacity: Var[float] | float | None = None,
        frost: Var[float] | float | None = None,
        elevation: Var[float] | float | None = None,
        padding: Var[float] | float | None = None,
        fuse: Var[bool] | bool | None = None,
        draggable: Var[bool] | bool | None = None,
        snap: Var[bool] | bool | None = None,
        group: Var[str] | str | None = None,
        bounds_selector: Var[str] | str | None = None,
        offset: Var[dict[str, float]] | dict[str, float] | None = None,
        default_offset: Var[dict[str, float]] | dict[str, float] | None = None,
        form_in: Var[bool] | bool | None = None,
        form_out: Var[bool] | bool | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_drag_end: EventType[()] | EventType[rx.Var[dict[str, float]]] | None = None,
        on_drag_start: EventType[()] | None = None,
        on_focus: EventType[()] | None = None,
        on_formed: EventType[()] | None = None,
        on_forming: EventType[()] | None = None,
        on_join_change: EventType[()] | EventType[bool] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> Plasma:
        """Create the component.

        Args:
            *children: The children of the component.
            as_: Element to render, e.g. "header", "nav", "section", "a". Default "div".
            radius: Corner radius (px). Default: the provider's.
            lean: Lean toward the pointer while standalone (px); False disables. Default 10.
            tint: Tint color (hex) for this surface.
            opacity: Tint strength for this surface, 0-1.
            frost: Frost for this surface, 0-1.
            elevation: Elevation for this surface, 0-1. Raises while dragging.
            padding: Inner padding (px); halves on joined edges.
            fuse: False: never blends or joins - for bars, docks, fixed chrome. Default True.
            draggable: Move freely, snap on release; arrow keys move one grid step.
            snap: Latch to neighbour edges, else the grid. Default True.
            group: Snap only against surfaces of the same group.
            bounds_selector: CSS selector of the drag area / grid origin, e.g. "#stage". Default: the viewport.
            offset: Controlled offset {x, y}; changes spring into place.
            default_offset: Initial offset {x, y} when uncontrolled.
            form_in: Override the provider's form-in for this surface.
            form_out: Override the provider's form-out for this surface.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            on_drag_start: Drag started.
            on_drag_end: Drag released; gets the settled {x, y}.
            on_join_change: Fused with / separated from a neighbour.
            on_forming: The form-in started.
            on_formed: The form-in settled - reveal contents here.
            **props: The props of the component.

        Returns:
            The component.
        """

class PlasmaCanvas(_PlasmaBase):
    def add_custom_code(self) -> list[str]: ...
    @classmethod
    def create(
        cls,
        *children,
        z_index: Var[int] | int | None = None,
        canvas_style: Var[dict[str, Any]] | dict[str, Any] | None = None,
        style: Sequence[Mapping[str, Any]]
        | Mapping[str, Any]
        | Var[Mapping[str, Any]]
        | Breakpoints
        | None = None,
        key: Any | None = None,
        id: Any | None = None,
        ref: Var | None = None,
        class_name: Any | None = None,
        custom_attrs: dict[str, Any | Var] | None = None,
        on_blur: EventType[()] | None = None,
        on_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_context_menu: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_double_click: EventType[()] | EventType[PointerEventInfo] | None = None,
        on_focus: EventType[()] | None = None,
        on_mount: EventType[()] | None = None,
        on_mouse_down: EventType[()] | None = None,
        on_mouse_enter: EventType[()] | None = None,
        on_mouse_leave: EventType[()] | None = None,
        on_mouse_move: EventType[()] | None = None,
        on_mouse_out: EventType[()] | None = None,
        on_mouse_over: EventType[()] | None = None,
        on_mouse_up: EventType[()] | None = None,
        on_scroll: EventType[()] | None = None,
        on_scroll_end: EventType[()] | None = None,
        on_unmount: EventType[()] | None = None,
        **props,
    ) -> PlasmaCanvas:
        """Create the component.

        Args:
            *children: The children of the component.
            z_index: Canvas z-index. Default -1.
            canvas_style: Inline style for the canvas (camelCase keys), e.g. {"position": "absolute", "zIndex": 1}.
            style: The style of the component.
            key: A unique key for the component.
            id: The id for the component.
            ref: The Var to pass as the ref to the component.
            class_name: The class name for the component.
            custom_attrs: Attributes passed directly to the component.
            on_focus: Fired when the element (or some element inside of it) receives focus. For example, it is called when the user clicks on a text input.
            on_blur: Fired when focus has left the element (or left some element inside of it). For example, it is called when the user clicks outside of a focused text input.
            on_click: Fired when the user clicks on an element. For example, it's called when the user clicks on a button.
            on_context_menu: Fired when the user right-clicks on an element.
            on_double_click: Fired when the user double-clicks on an element.
            on_mouse_down: Fired when the user presses a mouse button on an element.
            on_mouse_enter: Fired when the mouse pointer enters the element.
            on_mouse_leave: Fired when the mouse pointer leaves the element.
            on_mouse_move: Fired when the mouse pointer moves over the element.
            on_mouse_out: Fired when the mouse pointer moves out of the element.
            on_mouse_over: Fired when the mouse pointer moves onto the element.
            on_mouse_up: Fired when the user releases a mouse button on an element.
            on_scroll: Fired when the user scrolls the element.
            on_scroll_end: Fired when scrolling ends on the element.
            on_mount: Fired when the component is mounted to the page.
            on_unmount: Fired when the component is removed from the page. Only called during navigation, not on page refresh.
            **props: The props of the component.

        Returns:
            The component.
        """

plasma_provider = PlasmaProvider.create
plasma = Plasma.create
plasma_canvas = PlasmaCanvas.create
